// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASrrVX5d3PqkHndUD2PRmecxfhI9SsqVA',
    appId: '1:960133857982:web:acecb3ae244feeae8594ef',
    messagingSenderId: '960133857982',
    projectId: 'flutter-ppb',
    authDomain: 'flutter-ppb.firebaseapp.com',
    storageBucket: 'flutter-ppb.appspot.com',
    measurementId: 'G-29X21H5344',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlXulTp5cmpp1u508wXnsYWPlJXuV80ys',
    appId: '1:960133857982:android:2c4a4607a38bed9a8594ef',
    messagingSenderId: '960133857982',
    projectId: 'flutter-ppb',
    storageBucket: 'flutter-ppb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2XQIuzPAQ0KSAEcHnQxeRQ5IA4hq7VJ8',
    appId: '1:960133857982:ios:6a048fadc8f75a168594ef',
    messagingSenderId: '960133857982',
    projectId: 'flutter-ppb',
    storageBucket: 'flutter-ppb.appspot.com',
    iosBundleId: 'com.example.praktikum08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2XQIuzPAQ0KSAEcHnQxeRQ5IA4hq7VJ8',
    appId: '1:960133857982:ios:6a048fadc8f75a168594ef',
    messagingSenderId: '960133857982',
    projectId: 'flutter-ppb',
    storageBucket: 'flutter-ppb.appspot.com',
    iosBundleId: 'com.example.praktikum08',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASrrVX5d3PqkHndUD2PRmecxfhI9SsqVA',
    appId: '1:960133857982:web:dd63b79720e616a18594ef',
    messagingSenderId: '960133857982',
    projectId: 'flutter-ppb',
    authDomain: 'flutter-ppb.firebaseapp.com',
    storageBucket: 'flutter-ppb.appspot.com',
    measurementId: 'G-HD5YSTF200',
  );
}
